import { StyleSheet, Platform, StatusBar } from "react-native";

// Colores para temas
const lightTheme = {
  background: "#F5F5F5",
  cardBackground: "#fff",
  textPrimary: "#333",
  textSecondary: "#666",
  border: "#ccc",
  buttonBackground: "#007BFF",
  inputBackground: "#fff",
  clearButtonBackground: "#e0e0e0",
};

const darkTheme = {
  background: "#121212",
  cardBackground: "#1e1e1e",
  textPrimary: "#ffffff",
  textSecondary: "#b3b3b3",
  border: "#444",
  buttonBackground: "#0d6efd",
  inputBackground: "#2c2c2c",
  clearButtonBackground: "#404040",
};

// Función para crear estilos dinámicos
export const createStyles = (isDark: boolean) => {
  const theme = isDark ? darkTheme : lightTheme;
  
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      padding: 15,
      backgroundColor: theme.background,
    },
    appTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.textPrimary,
      textAlign: "center",
      marginBottom: 15,
      marginTop: 10,
      includeFontPadding: false,
      textAlignVertical: 'center',
    },
    input: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      padding: 12,
      backgroundColor: theme.inputBackground,
      marginBottom: 10,
      color: theme.textPrimary,
    },
    inputContainer: {
      position: "relative",
      marginBottom: 10,
    },
    inputWithClear: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      padding: 12,
      paddingRight: 40,
      backgroundColor: theme.inputBackground,
      color: theme.textPrimary,
    },
    clearButton: {
      position: "absolute",
      right: 10,
      top: "50%",
      transform: [{ translateY: -12 }],
      width: 24,
      height: 24,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.clearButtonBackground,
      borderRadius: 12,
    },
    clearButtonText: {
      color: theme.textSecondary,
      fontSize: 14,
      fontWeight: "bold",
    },
    suggestionItem: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      backgroundColor: theme.cardBackground,
    },
    suggestionText: {
      color: theme.textPrimary,
    },
    buttonsRow: {
      flexDirection: "row",
      justifyContent: "flex-start",
      marginVertical: 10,
      flexWrap: "wrap",
    },
    sortButtonsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginVertical: 10,
    },
    sortButton: {
      backgroundColor: theme.buttonBackground,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 3,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 40,
    },
    sortButtonText: {
      color: "#fff",
      fontWeight: "600",
      textAlign: "center",
      fontSize: 10,
      includeFontPadding: false,
      textAlignVertical: 'center',
      lineHeight: 12,
    },
    mapViewButton: {
      backgroundColor: "#4285F4",
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 3,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 40,
    },
    mapViewButtonText: {
      color: "#fff",
      fontWeight: "600",
      textAlign: "center",
      fontSize: 10,
      includeFontPadding: false,
      textAlignVertical: 'center',
      lineHeight: 12,
    },
    button: {
      backgroundColor: theme.buttonBackground,
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 8,
    },
    buttonText: {
      color: "#fff",
      fontWeight: "bold",
    },
    card: {
      flexDirection: "row",
      backgroundColor: theme.cardBackground,
      marginVertical: 6,
      borderRadius: 10,
      elevation: 2,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 5,
      overflow: "hidden",
    },
    image: {
      width: 100,
      height: 100,
    },
    cardContent: {
      flex: 1,
      padding: 10,
      justifyContent: "center",
    },
    hotelName: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.textPrimary,
      includeFontPadding: false,
      lineHeight: 18,
    },
    hotelVicinity: {
      fontSize: 13,
      color: theme.textSecondary,
      marginVertical: 2,
      includeFontPadding: false,
      lineHeight: 16,
    },
    hotelRating: {
      fontSize: 13,
      color: "#FFA500",
      marginTop: 4,
      includeFontPadding: false,
      lineHeight: 16,
    },
    mapButton: {
      backgroundColor: "#28a745",
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginRight: 6,
      marginBottom: 8,
      minWidth: 90,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mapButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 11,
      textAlign: 'center',
      includeFontPadding: false,
      textAlignVertical: 'center',
    },
    item: {
      padding: 12,
      borderBottomWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.cardBackground,
    },
    itemTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.textPrimary,
    },
    expandedText: {
      color: theme.textPrimary,
    },
    favoriteButton: {
      backgroundColor: theme.clearButtonBackground,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginRight: 6,
      marginBottom: 8,
      minWidth: 80,
      alignItems: 'center',
      justifyContent: 'center',
    },
    favoriteButtonActive: {
      backgroundColor: '#FFD700',
    },
    favoriteButtonText: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 11,
      textAlign: 'center',
      includeFontPadding: false,
      textAlignVertical: 'center',
    },
    reserveButton: {
      backgroundColor: '#FF6B35',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginRight: 6,
      marginBottom: 8,
      minWidth: 90,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reserveButtonText: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 11,
      textAlign: 'center',
      includeFontPadding: false,
      textAlignVertical: 'center',
    },
    favoritesHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 15,
    },
    closeButton: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: theme.clearButtonBackground,
      justifyContent: 'center',
      alignItems: 'center',
    },
    closeButtonText: {
      color: theme.textSecondary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    emptyFavorites: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 100,
    },
    emptyFavoritesText: {
      fontSize: 18,
      color: theme.textPrimary,
      marginBottom: 10,
      textAlign: 'center',
    },
    emptyFavoritesSubtext: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: 'center',
    },
    webView: {
      flex: 1,
      borderRadius: 10,
      marginVertical: 10,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.background,
    },
    loadingText: {
      marginTop: 10,
      fontSize: 16,
      color: theme.textPrimary,
    },
    emptyMap: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 100,
    },
    emptyMapText: {
      fontSize: 18,
      color: theme.textPrimary,
      textAlign: 'center',
      paddingHorizontal: 20,
    },
  });
};

// Mantener estilos estáticos para compatibilidad hacia atrás
export const styles = createStyles(false);